### PR TITLE
Date support, Code cleanup

### PR DESCRIPTION
**Pull request by kwestground**

### CODE REVIEW

**Comment by rmorrin** [comment]
Thanks for the PR - Awesome work! 👍 

I wonder if we should expose the date as a property on `ExchangeRate`. What do you think?

**Comment by kwestground** [comment]
Sure why not!

**Comment by rmorrin** [comment]
Do you want to make the change? Will be happy to merge this afterwards

**Comment by rmorrin** [comment]
Do you want to make these changes? I'll be happy to merge afterwards 👍 

Didn't mean to close the PR either :smile

**Pull request merged**
